import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#faf6f0",
  },
  topBar: {
    height: 92,
    paddingTop: 40,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#f4efe6",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(74, 124, 89, 0.08)",
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(74, 124, 89, 0.08)",
  },
  iconText: {
    color: "#705c30",
    fontSize: 18,
    fontWeight: "700",
    lineHeight: 18,
  },
  topBarTitle: {
    color: "#705c30",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 2,
  },
  loadingWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  loadingText: {
    marginTop: 14,
    color: "#705c30",
    fontSize: 15,
    textAlign: "center",
  },
  errorText: {
    color: "#8b3f3f",
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 12,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
    gap: 12,
  },
  scoreboardCard: {
    position: "relative",
    overflow: "hidden",
    backgroundColor: "#f7f2ea",
    borderRadius: 14,
    padding: 20,
    shadowColor: "#2e3230",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 2,
  },
  glowOrb: {
    position: "absolute",
    top: -24,
    right: -18,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(112, 92, 48, 0.08)",
  },
  scoreboardInner: {
    alignItems: "center",
  },
  matchStamp: {
    color: "#4a7c59",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 2,
    marginBottom: 8,
  },
  scoreboardNote: {
    color: "#7b7468",
    fontSize: 13,
    marginBottom: 24,
  },
  versusRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  teamBlock: {
    flex: 1,
    alignItems: "center",
  },
  teamBadge: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "#fbf7f1",
    borderWidth: 1,
    borderColor: "rgba(74, 124, 89, 0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  teamBadgeText: {
    color: "#2f3c33",
    fontSize: 24,
    fontWeight: "800",
  },
  teamCaption: {
    color: "#8b867c",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.4,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  teamFullName: {
    color: "#2f3c33",
    fontSize: 16,
    fontWeight: "700",
    textAlign: "center",
  },
  vsBlock: {
    paddingHorizontal: 12,
    alignItems: "center",
  },
  vsText: {
    color: "#705c30",
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 4,
  },
  vsSubText: {
    color: "#8b867c",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.4,
  },
  traitWrap: {
    width: "100%",
    marginTop: 4,
  },
  traitText: {
    color: "#5d5a54",
    fontSize: 14,
    lineHeight: 22,
    textAlign: "center",
  },
  traitTextSpacing: {
    marginTop: 16,
  },
  lineupHeader: {
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(74, 124, 89, 0.1)",
  },
  lineupTitle: {
    color: "#2f3c33",
    fontSize: 24,
    fontWeight: "800",
  },
  column: {
    backgroundColor: "#f7f2ea",
    borderRadius: 14,
    padding: 14,
    shadowColor: "#2e3230",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 2,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    paddingHorizontal: 2,
  },
  sectionAccent: {
    width: 4,
    height: 18,
    borderRadius: 2,
    marginRight: 10,
  },
  sectionHeaderTitle: {
    flex: 1,
    color: "#3c453d",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.4,
  },
  sectionCount: {
    minWidth: 28,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    alignItems: "center",
  },
  countPrimary: {
    backgroundColor: "rgba(74, 124, 89, 0.12)",
  },
  countMuted: {
    backgroundColor: "rgba(74, 124, 89, 0.07)",
  },
  countAmber: {
    backgroundColor: "rgba(112, 92, 48, 0.12)",
  },
  sectionCountText: {
    color: "#705c30",
    fontSize: 11,
    fontWeight: "800",
  },
  playerCard: {
    backgroundColor: "#fffaf2",
    borderRadius: 18,
    padding: 16,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "rgba(74, 124, 89, 0.06)",
  },
  playerCardStrong: {
    backgroundColor: "#fcf8f2",
  },
  playerCardDimmed: {
    opacity: 0.62,
  },
  playerCardAccent: {
    borderLeftWidth: 3,
    borderLeftColor: "#705c30",
    backgroundColor: "#fffdf9",
    opacity: 0.5,
  },
  playerTextWrap: {
    flex: 1,
    paddingRight: 12,
  },
  playerName: {
    color: "#2f3c33",
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 4,
  },
  playerNameDimmed: {
    color: "#7e796e",
  },
  playerMeta: {
    color: "#8b867c",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.2,
  },
  playerTag: {
    color: "#4a7c59",
    fontSize: 24,
    fontWeight: "800",
    opacity: 0.45,
  },
  emptyText: {
    color: "#8b867c",
    fontSize: 13,
    lineHeight: 20,
    paddingHorizontal: 2,
  },
  moreButton: {
    marginTop: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#d4ccc0",
    backgroundColor: "#fdf9f3",
    paddingVertical: 10,
    alignItems: "center",
  },
  moreText: {
    color: "#4a7c59",
    fontSize: 13,
    fontWeight: "700",
  },
  backButton: {
    minHeight: 58,
    borderRadius: 18,
    backgroundColor: "#4a7c59",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#2e3230",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 2,
  },
  backButtonArrow: {
    color: "#faf6f0",
    fontSize: 18,
    fontWeight: "800",
    marginRight: 8,
  },
  backButtonText: {
    color: "#faf6f0",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 2,
  },
});
