import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#faf6f0",
  },
  body: {
    flex: 1,
    position: "relative",
  },
  calendarSection: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 8,
    backgroundColor: "#faf6f0",
    zIndex: 10,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 295,
    paddingBottom: 120,
    gap: 14,
  },
  sectionCard: {
    backgroundColor: "#f7f2ea",
    borderRadius: 18,
    padding: 16,
    shadowColor: "#2e3230",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 2,
  },
  calendarCard: {
    padding: 13,
    paddingBottom: 11,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  sectionEyebrow: {
    color: "#8c8478",
    fontSize: 11,
    fontWeight: "700",
    marginBottom: 7,
  },
  sectionTitle: {
    color: "#2e322f",
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "800",
  },
  calendarTitle: {
    color: "#2e322f",
    fontSize: 20,
    fontWeight: "700",
  },
  calendarTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  todayButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(74, 124, 89, 0.08)",
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(74, 124, 89, 0.16)",
  },
  todayButtonText: {
    color: "#4a7c59",
    fontSize: 11,
    fontWeight: "800",
  },
  calendarBody: {
    position: "relative",
  },
  calendarSideButton: {
    position: "absolute",
    top: "50%",
    marginTop: -38,
    height: 76,
    width: 14,
    borderRadius: 10,
    backgroundColor: "#f7f2ea",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  calendarSideButtonLeft: {
    left: -8,
  },
  calendarSideButtonRight: {
    right: -8,
  },
  calendarSideArrow: {
    color: "#a6a29b",
    fontSize: 28,
    lineHeight: 40,
    fontWeight: "700",
    marginTop: -1,
  },
  weekHeader: {
    flexDirection: "row",
    marginBottom: 6,
  },
  weekDay: {
    width: `${100 / 7}%`,
    textAlign: "center",
    fontSize: 14,
    color: "#99948d",
    fontWeight: "700",
  },
  weekRow: {
    flexDirection: "row",
    marginBottom: 2,
  },
  dayCell: {
    width: `${100 / 7}%`,
    alignItems: "center",
  },
  dayCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  dayEvent: {
    backgroundColor: "#e4ecd9",
  },
  dayToday: {
    borderWidth: 1,
    borderColor: "#7a9a74",
  },
  dayText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#3a3f3b",
  },
  dayDim: {
    color: "#c1bcb4",
  },
  countBadge: {
    minWidth: 64,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: "#ebe3d6",
  },
  countBadgeText: {
    color: "#4a7c59",
    fontSize: 12,
    fontWeight: "800",
  },
  loader: {
    marginTop: 18,
    marginBottom: 6,
  },
  scheduleList: {
    marginTop: 18,
    gap: 12,
  },
  tabContainer: {
    flexDirection: "row",
    backgroundColor: "#ebe3d6",
    borderRadius: 14,
    padding: 4,
    marginTop: 18,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    borderRadius: 10,
  },
  activeTab: {
    backgroundColor: "#ffffff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  tabText: {
    fontSize: 13,
    fontWeight: "800",
    color: "#7a736a",
  },
  activeTabText: {
    color: "#e76f51",
  },
  scheduleItem: {
    gap: 12,
    padding: 14,
    borderRadius: 16,
    backgroundColor: "#fcf8f2",
    borderWidth: 1,
    borderColor: "rgba(112, 92, 48, 0.08)",
  },
  scheduleItemRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  scheduleItemHighlight: {
    borderColor: "#e76f51",
    backgroundColor: "#fffafa",
    elevation: 5,
    borderWidth: 1.8,
  },
  scheduleIndexBadge: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#dfe8d7",
  },
  scheduleIndexText: {
    color: "#4a7c59",
    fontSize: 13,
    fontWeight: "800",
  },
  scheduleMain: {
    flex: 1,
    gap: 4,
  },
  scheduleMatchText: {
    color: "#2e322f",
    fontSize: 17,
    lineHeight: 24,
    fontWeight: "700",
  },
  scheduleMatchTextHighlight: {
    color: "#e76f51",
  },
  scheduleDateRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  scheduleDateText: {
    color: "#7a736a",
    fontSize: 13,
    lineHeight: 18,
    flex: 1,
  },
  scheduleScoreText: {
    color: "#7a736a",
    fontSize: 14,
    fontWeight: "800",
  },
  loadMoreButton: {
    marginTop: 16,
    minHeight: 50,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#4a7c59",
  },
  loadMoreButtonText: {
    color: "#faf6f0",
    fontSize: 15,
    fontWeight: "800",
  },
  emptyText: {
    marginTop: 18,
    color: "#7a736a",
    fontSize: 14,
    lineHeight: 22,
  },
  errorText: {
    marginTop: 18,
    color: "#8b3f3f",
    fontSize: 14,
    lineHeight: 22,
  },
});
