import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#faf6f0",
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 28,
    gap: 14,
  },
  heroCard: {
    backgroundColor: "#f7f2ea",
    borderRadius: 20,
    paddingTop: 16,
    paddingBottom: 16,
    paddingHorizontal: 12,
    gap: 12,
    shadowColor: "#2e3230",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 2,
  },
  heroImageSlot: {
    height: 210,
    borderRadius: 18,
    overflow: "hidden",
    justifyContent: "flex-end",
    marginHorizontal: -2,
    backgroundColor: "#d9d2c3",
    borderWidth: 1,
    borderColor: "rgba(112, 92, 48, 0.16)",
  },
  heroImage: {
    borderRadius: 18,
  },
  heroImageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(46, 50, 47, 0.28)",
  },
  heroEyebrow: {
    color: "#705c30",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  heroTitle: {
    color: "#2e322f",
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "800",
  },
  heroBottomLabel: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "flex-end",
    paddingHorizontal: 10,
    paddingVertical: 10,
    zIndex: 1,
  },
  heroBottomLabelText: {
    color: "#2e322f",
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "800",
    textAlign: "right",
    backgroundColor: "#ebe3d6",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 7,
    overflow: "hidden",
  },
  sectionCard: {
    backgroundColor: "#f7f2ea",
    borderRadius: 18,
    padding: 16,
    shadowColor: "#2e3230",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 2,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  sectionEyebrow: {
    color: "#705c30",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  sectionTitle: {
    color: "#2e322f",
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "800",
  },
  countBadge: {
    minWidth: 64,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: "#ebe3d6",
  },
  countBadgeText: {
    color: "#4a7c59",
    fontSize: 12,
    fontWeight: "800",
  },
  loader: {
    marginTop: 18,
    marginBottom: 6,
  },
  nearestCard: {
    marginTop: 18,
    borderRadius: 16,
    padding: 18,
    backgroundColor: "#ede4d7",
    borderWidth: 1,
    borderColor: "rgba(74, 124, 89, 0.14)",
    gap: 10,
  },
  nearestMatchText: {
    color: "#2e322f",
    fontSize: 24,
    lineHeight: 32,
    fontWeight: "800",
  },
  vsText: {
    color: "#4a7c59",
  },
  nearestDateText: {
    color: "#705c30",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  scheduleList: {
    marginTop: 18,
    gap: 10,
  },
  scheduleItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 16,
    backgroundColor: "#fcf8f2",
    borderWidth: 1,
    borderColor: "rgba(112, 92, 48, 0.08)",
  },
  scheduleItemHighlight: {
    borderColor: "rgba(74, 124, 89, 0.22)",
    backgroundColor: "#f4efe5",
  },
  scheduleIndexBadge: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#dfe8d7",
  },
  scheduleIndexText: {
    color: "#4a7c59",
    fontSize: 13,
    fontWeight: "800",
  },
  scheduleMain: {
    flex: 1,
    gap: 4,
  },
  scheduleMatchText: {
    color: "#2e322f",
    fontSize: 17,
    lineHeight: 24,
    fontWeight: "700",
  },
  scheduleDateText: {
    color: "#7a736a",
    fontSize: 13,
    lineHeight: 18,
  },
  loadMoreButton: {
    marginTop: 16,
    minHeight: 50,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#4a7c59",
  },
  loadMoreButtonText: {
    color: "#faf6f0",
    fontSize: 15,
    fontWeight: "800",
  },
  emptyText: {
    marginTop: 18,
    color: "#7a736a",
    fontSize: 14,
    lineHeight: 22,
  },
  errorText: {
    marginTop: 18,
    color: "#8b3f3f",
    fontSize: 14,
    lineHeight: 22,
  },
});
