import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#faf6f0",
  },
  loadingWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  loadingText: {
    color: "#6f6a62",
    fontSize: 14,
    fontWeight: "600",
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 110,
    gap: 12,
  },
  errorText: {
    color: "#8b3f3f",
    fontSize: 12,
    lineHeight: 18,
  },
  card: {
    backgroundColor: "#f7f2ea",
    borderRadius: 16,
    padding: 16,
    shadowColor: "#2e3230",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 2,
  },
  cardEyebrow: {
    color: "#8c8478",
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 6,
  },
  cardTitle: {
    color: "#2e322f",
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 12,
  },
  vsTitle: {
    color: "#2e322f",
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "800",
    marginBottom: 14,
  },
  matchMetaBlock: {
    gap: 8,
  },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(112, 92, 48, 0.1)",
  },
  metaLabel: {
    color: "#8f887e",
    fontSize: 13,
    fontWeight: "700",
  },
  metaValue: {
    color: "#2f3431",
    fontSize: 14,
    fontWeight: "700",
    flexShrink: 1,
    textAlign: "right",
  },
  sectionBlock: {
    marginTop: 8,
    marginBottom: 0,
  },
  sectionTitle: {
    color: "#4a7c59",
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 8,
  },
  fieldCard: {
    backgroundColor: "#fdf9f3",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 16,
    alignItems: "center",
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(74, 124, 89, 0.08)",
  },
  diamond: {
    width: "100%",
    alignItems: "center",
  },
  fieldRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    marginVertical: 6,
  },
  dhWrap: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: "rgba(112, 92, 48, 0.1)",
    width: "100%",
    alignItems: "center",
    paddingTop: 10,
  },
  slot: {
    minWidth: 72,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: "center",
    backgroundColor: "rgba(74, 124, 89, 0.04)",
  },
  slotHighlight: {
    backgroundColor: "rgba(74, 124, 89, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(74, 124, 89, 0.18)",
  },
  slotPos: {
    color: "#705c30",
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 4,
  },
  slotName: {
    color: "#2f3431",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  benchText: {
    color: "#705c30",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 2,
  },
  emptyText: {
    color: "#8f887e",
    fontSize: 13,
    lineHeight: 18,
  },
  playerCard: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(112, 92, 48, 0.1)",
  },
  playerName: {
    color: "#2f3431",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 3,
  },
  playerMeta: {
    color: "#8f887e",
    fontSize: 12,
    fontWeight: "600",
  },
  backButton: {
    marginTop: 2,
    marginBottom: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#d4ccc0",
    backgroundColor: "#fdf9f3",
    paddingVertical: 12,
    alignItems: "center",
  },
  backButtonText: {
    color: "#4a7c59",
    fontSize: 14,
    fontWeight: "700",
  },
});
