import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#faf6f0",
  },
  loadingWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  loadingText: {
    color: "#6f6a62",
    fontSize: 14,
    fontWeight: "600",
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 0,
    paddingTop: 10,
    paddingBottom: 110,
    gap: 12,
  },
  errorText: {
    color: "#8b3f3f",
    fontSize: 12,
    lineHeight: 18,
    paddingHorizontal: 16,
  },
  heroCard: {
    backgroundColor: "#f7f2ea",
    borderRadius: 20,
    paddingTop: 16,
    paddingBottom: 16,
    paddingHorizontal: 12,
    marginHorizontal: 16,
    gap: 12,
    shadowColor: "#2e3230",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 2,
  },
  heroImageSlot: {
    height: 210,
    borderRadius: 18,
    overflow: "hidden",
    justifyContent: "flex-end",
    marginHorizontal: -2,
    backgroundColor: "#d9d2c3",
    borderWidth: 1,
    borderColor: "rgba(112, 92, 48, 0.16)",
  },
  heroImage: {
    borderRadius: 18,
  },
  heroImageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(46, 50, 47, 0.28)",
  },
  heroEyebrow: {
    color: "#705c30",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  heroTitle: {
    color: "#2e322f",
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "800",
  },
  heroBottomLabel: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "flex-end",
    paddingHorizontal: 10,
    paddingVertical: 10,
    zIndex: 1,
  },
  heroBottomLabelText: {
    color: "#2e322f",
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "800",
    textAlign: "right",
    backgroundColor: "#ebe3d6",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 7,
    overflow: "hidden",
  },
  card: {
    backgroundColor: "#f7f2ea",
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    shadowColor: "#2e3230",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 2,
  },
  cardEyebrow: {
    color: "#8c8478",
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 6,
  },
  cardTitle: {
    color: "#2e322f",
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 12,
  },
  nearestCard: {
    marginTop: 6,
    borderRadius: 16,
    padding: 18,
    backgroundColor: "#ede4d7",
    borderWidth: 1,
    borderColor: "rgba(74, 124, 89, 0.14)",
    gap: 10,
  },
  nearestMatchText: {
    color: "#2e322f",
    fontSize: 24,
    lineHeight: 32,
    fontWeight: "800",
  },
  vsText: {
    color: "#4a7c59",
  },
  nearestDateText: {
    color: "#705c30",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  vsTitle: {
    color: "#2e322f",
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "800",
    marginBottom: 14,
  },
  matchMetaBlock: {
    gap: 8,
  },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(112, 92, 48, 0.1)",
  },
  metaLabel: {
    color: "#8f887e",
    fontSize: 13,
    fontWeight: "700",
  },
  metaValue: {
    color: "#2f3431",
    fontSize: 14,
    fontWeight: "700",
    flexShrink: 1,
    textAlign: "right",
  },
  sectionBlock: {
    marginTop: 8,
    marginBottom: 0,
  },
  sectionTitle: {
    color: "#4a7c59",
    fontSize: 18,
    fontWeight: "800",
  },
  fieldSection: {
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  fieldCard: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 16,
    alignItems: "center",
    shadowColor: "#2e3230",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 4,
  },
  sectionHeader: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  badge: {
    backgroundColor: "rgba(74, 124, 89, 0.1)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  badgeText: {
    color: "#4a7c59",
    fontSize: 12,
    fontWeight: "800",
  },
  diamond: {
    width: "100%",
    alignItems: "center",
  },
  fieldRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    marginVertical: 6,
  },

  // --- 상단: 베스트 라인업 (야구장 UI) ---
  fieldContainer: {
    // width: width - (fieldSection: 16*2) - (fieldCard: 16*2) = width - 64
    width: width - 64,
    height: (width - 64) * 1.1,
    backgroundColor: "#1d3557",
    borderRadius: 20,
    overflow: "hidden",
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  stadiumFan: {
    width: (width - 64) * 1.6,
    height: (width - 64) * 1.6,
    backgroundColor: "#76c893",
    borderRadius: (width - 64) * 0.8,
    position: "absolute",
    top: -((width - 64) * 0.4),
    transform: [{ rotate: "45deg" }],
    borderWidth: 2,
    borderColor: "#ffffff",
  },
  infieldDirtSemi: {
    position: "absolute",
    bottom: "5%",
    width: (width - 64) * 0.75,
    height: (width - 64) * 0.75,
    backgroundColor: "#f4a261",
    borderRadius: (width - 64) * 0.375,
    alignSelf: "center",
  },
  diamondBaseLines: {
    position: "absolute",
    bottom: "12%",
    width: (width - 64) * 0.4,
    height: (width - 64) * 0.4,
    borderWidth: 4,
    borderColor: "#ffffff",
    transform: [{ rotate: "45deg" }],
    backgroundColor: "#52b788",
  },
  pitcherMoundDirt: {
    position: "absolute",
    top: "60%",
    left: "40%",
    width: "20%",
    height: "20%",
    backgroundColor: "#e76f51",
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  moundPlate: {
    width: "60%",
    height: "15%",
    backgroundColor: "#ffffff",
  },
  baseMarker: {
    position: "absolute",
    width: 12,
    height: 12,
    backgroundColor: "#ffffff",
    transform: [{ rotate: "45deg" }],
    zIndex: 5,
  },
  base1B: { bottom: "31.1%", right: "21.7%", marginRight: -6 },
  base2B: { bottom: "56.8%", alignSelf: "center", marginBottom: -6 },
  base3B: { bottom: "31.1%", left: "21.7%", marginLeft: -6 },
  baseHome: {
    position: "absolute",
    bottom: "5.4%",
    alignSelf: "center",
    width: 16,
    height: 16,
    backgroundColor: "#ffffff",
    transform: [{ rotate: "45deg" }],
  },

  // 포지션 슬롯 좌표
  posP: { position: "absolute", bottom: "25%", alignSelf: "center" },
  posC: { position: "absolute", bottom: "3%", alignSelf: "center" },
  pos1B: { position: "absolute", bottom: "38%", right: "5%" },
  pos2B: { position: "absolute", bottom: "50%", right: "24%" },
  pos3B: { position: "absolute", bottom: "38%", left: "5%" },
  posSS: { position: "absolute", bottom: "50%", left: "25%" },
  posLF: { position: "absolute", bottom: "70%", left: "12%" },
  posCF: { position: "absolute", bottom: "82%", alignSelf: "center" },
  posRF: { position: "absolute", bottom: "70%", right: "12%" },
  posDH: { position: "absolute", bottom: "15%", right: "5%" },

  slotStadium: {
    paddingHorizontal: 6,
    paddingVertical: 5,
    alignItems: "center",
    minWidth: 55,
    borderRadius: 8,
    backgroundColor: "rgba(255, 255, 255, 1)",
    borderWidth: 1.5,
    borderColor: "#1d3557",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  slotHighlightStadium: {
    borderColor: "#e76f51",
    borderWidth: 2,
    elevation: 5,
    backgroundColor: "#fffdfb",
  },
  slotAvatarContainer: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#f0f7f2",
    overflow: "hidden",
    marginBottom: 4,
    borderWidth: 1.2,
    borderColor: "rgba(74, 124, 89, 0.1)",
  },
  slotBottomRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  slotNameStadium: {
    fontSize: 10,
    fontWeight: "800",
    color: "#1d3557",
  },
  slotNameHighlightStadium: {
    color: "#e76f51",
  },
  slotPosStadium: {
    fontSize: 7.5,
    fontWeight: "900",
    color: "#e76f51",
    backgroundColor: "rgba(231, 111, 81, 0.1)",
    paddingHorizontal: 3,
    paddingVertical: 0.5,
    borderRadius: 3,
  },

  dhWrap: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: "rgba(112, 92, 48, 0.1)",
    width: "100%",
    alignItems: "center",
    paddingTop: 10,
  },
  slot: {
    minWidth: 72,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: "center",
    backgroundColor: "rgba(74, 124, 89, 0.04)",
  },
  slotHighlight: {
    backgroundColor: "rgba(74, 124, 89, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(74, 124, 89, 0.18)",
  },
  slotPos: {
    color: "#705c30",
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 4,
  },
  slotName: {
    color: "#2f3431",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  benchText: {
    color: "#705c30",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 2,
  },
  emptyText: {
    color: "#8f887e",
    fontSize: 13,
    lineHeight: 18,
  },
  rosterGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    gap: 10,
    marginTop: 15,
  },
  playerCard: {
    width: (width - 40 - 44) / 3, // Padding and gaps considered
    backgroundColor: "rgba(74, 124, 89, 0.04)",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 6,
    alignItems: "center",
    marginBottom: 5,
    borderWidth: 1,
    borderColor: "rgba(74, 124, 89, 0.08)",
  },
  playerName: {
    color: "#2f3431",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
  },
  playerAvatarContainer: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#ffffff",
    overflow: "hidden",
    borderWidth: 1.5,
    borderColor: "#ffffff",
    marginBottom: 8,
    // Subtle shadow for avatar
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  playerMeta: {
    color: "#8f887e",
    fontSize: 10,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 2,
  },
  backButtonText: {
    color: "#4a7c59",
    fontSize: 14,
    fontWeight: "700",
  },
});
