import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#faf6f0",
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 24,
    gap: 12,
  },
  pageHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  pageTitle: {
    flex: 1,
    fontSize: 30,
    lineHeight: 34,
    color: "#2e322f",
    fontWeight: "700",
    marginBottom: 2,
  },
  switchUserButton: {
    borderWidth: 1,
    borderColor: "#b7c8b0",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#fdf9f3",
  },
  switchUserText: {
    color: "#4a7c59",
    fontSize: 11,
    fontWeight: "700",
  },
  errorText: {
    color: "#8b3f3f",
    fontSize: 12,
    lineHeight: 18,
  },
  card: {
    backgroundColor: "#f7f2ea",
    borderRadius: 14,
    padding: 14,
    shadowColor: "#2e3230",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 24,
    color: "#2e322f",
    fontWeight: "700",
    marginBottom: 20,
  },
  gameHero: {
    height: 132,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    overflow: "hidden",
  },
  gameHeroImage: {
    borderRadius: 12,
  },
  gameHeroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(46, 50, 47, 0.24)",
  },
  dateBadge: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#d5e4c3",
    alignItems: "center",
    justifyContent: "center",
  },
  dateDay: {
    fontSize: 13,
    fontWeight: "800",
    color: "#2d382f",
  },
  dateMonth: {
    fontSize: 8,
    fontWeight: "700",
    color: "#5f6f61",
    marginTop: -1,
  },
  metaRowInHero: {
    position: "absolute",
    left: 10,
    right: 10,
    bottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  metaChip: {
    backgroundColor: "#e6dfd2",
    color: "#8b805f",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 10,
    fontWeight: "700",
  },
  metaTimeInHero: {
    color: "#f5efe5",
    fontSize: 11,
    fontWeight: "700",
    textShadowColor: "rgba(0, 0, 0, 0.2)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  matchTitle: {
    textAlign: "center",
    fontSize: 20,
    lineHeight: 29,
    color: "#2e322f",
    fontWeight: "700",
  },
  matchSub: {
    fontSize: 12,
    color: "#7f786f",
    marginTop: 6,
    marginBottom: 12,
  },
  matchSubButton: {
    width: "100%",
    alignItems: "flex-end",
  },
  matchSubLink: {
    color: "#2f6f4f",
    textDecorationLine: "underline",
  },
  actionRow: {
    flexDirection: "row",
    gap: 8,
  },
  secondaryButton: {
    width: 90,
    backgroundColor: "#fdf9f3",
    borderWidth: 1,
    borderColor: "#b7c8b0",
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: "center",
  },
  detailButton: {
    width: "100%",
  },
  secondaryText: {
    color: "#4a7c59",
    fontSize: 12,
    fontWeight: "700",
  },
  detailButtonText: {
    fontSize: 16,
  },
  calendarHeader: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  calendarMonth: {
    color: "#2e322f",
    fontSize: 18,
    fontWeight: "700",
    minWidth: 110,
    textAlign: "center",
  },
  calendarMonthButton: {
    minHeight: 36,
    paddingHorizontal: 14,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fdf9f3",
    borderWidth: 1,
    borderColor: "#d4ccc0",
  },
  calendarArrowGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  calendarArrowButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fdf9f3",
    borderWidth: 1,
    borderColor: "#d4ccc0",
  },
  calendarArrow: {
    color: "#7b776f",
    fontSize: 26,
    fontWeight: "700",
  },
  weekHeader: {
    flexDirection: "row",
    marginBottom: 8,
  },
  weekDay: {
    width: `${100 / 7}%`,
    textAlign: "center",
    fontSize: 14,
    color: "#99948d",
    fontWeight: "700",
  },
  weekRow: {
    flexDirection: "row",
    marginBottom: 4,
  },
  dayCell: {
    width: `${100 / 7}%`,
    alignItems: "center",
  },
  dayCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  dayEvent: {
    backgroundColor: "#e4ecd9",
  },
  dayEventAttending: {
    backgroundColor: "#d9f1df",
  },
  dayEventPending: {
    backgroundColor: "#d1d1d1",
  },
  dayEventAbsent: {
    backgroundColor: "#f4dada",
  },
  daySelected: {
    borderWidth: 2,
    borderColor: "#9ebd8d",
  },
  dayToday: {
    borderWidth: 1,
    borderColor: "#a9a39a",
  },
  dayText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#3a3f3b",
  },
  dayDim: {
    color: "#c1bcb4",
  },
  daySelectedText: {
    color: "#2f6f4f",
  },
  loadingWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
  },
  loadingText: {
    color: "#6f6a62",
    fontSize: 12,
  },
  listItem: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(112, 92, 48, 0.14)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  listLeft: {
    flex: 1,
  },
  listDate: {
    color: "#9f988f",
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 3,
  },
  listOpponent: {
    color: "#2f3431",
    fontSize: 17,
    fontWeight: "700",
  },
  listTime: {
    color: "#8f887e",
    fontSize: 15,
    marginLeft: 8,
  },
  listRight: {
    alignItems: "flex-end",
    marginLeft: 8,
  },
  attendanceWrap: {
    marginTop: 8,
    alignItems: "flex-end",
    gap: 6,
  },
  attendanceBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  attendanceBadgeIcon: {
    fontSize: 16,
    fontWeight: "800",
  },
  attendanceBadgeText: {
    fontSize: 15,
    fontWeight: "700",
  },
  attendanceOptionRow: {
    flexDirection: "row",
    gap: 8,
    justifyContent: "flex-end",
  },
  attendanceOptionButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fdf9f3",
    borderWidth: 1,
    borderColor: "#ddd5c8",
  },
  attendanceOptionButtonSelected: {
    borderColor: "#7a9a74",
    backgroundColor: "#eef5e7",
  },
  attendanceOptionIcon: {
    fontSize: 13,
    fontWeight: "800",
  },
  savingText: {
    marginTop: 6,
    color: "#9f988f",
    fontSize: 14,
    fontWeight: "700",
  },
  moreButton: {
    marginTop: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#d4ccc0",
    backgroundColor: "#fdf9f3",
    paddingVertical: 10,
    alignItems: "center",
  },
  moreText: {
    color: "#4a7c59",
    fontSize: 13,
    fontWeight: "700",
  },
});
