import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#faf6f0",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    backgroundColor: "#faf6f0",
  },
  modeToggleContainer: {
    flexDirection: "row",
    backgroundColor: "rgba(74, 124, 89, 0.05)",
    borderRadius: 8,
    padding: 2,
    marginRight: 4,
  },
  modeToggleButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  modeToggleButtonActive: {
    backgroundColor: "#ffffff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  modeToggleText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#705c30",
  },
  modeToggleTextActive: {
    color: "#4a7c59",
  },
  headerRight: {
    fontSize: 10,
    fontWeight: "700",
    color: "#705c30",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  heroSection: {
    marginTop: 8,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 24,
    shadowColor: "rgba(46, 50, 48, 1)",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 4,
    width: "100%",
  },
  largeTeamName: {
    fontSize: 16,
    fontWeight: "800",
    color: "#4a7c59",
    letterSpacing: 1.2,
    marginBottom: 10,
    textTransform: "uppercase",
  },
  heroMainRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 20,
  },
  heroNumber: {
    fontSize: 22,
    fontWeight: "700",
    color: "rgba(74, 124, 89, 0.4)",
    marginBottom: -4,
  },
  heroName: {
    fontSize: 38,
    fontWeight: "800",
    color: "#2e3230",
    fontFamily: "serif",
  },
  orderBadgeContainer: {
    backgroundColor: "rgba(112, 92, 48, 0.1)",
    borderWidth: 1.5,
    borderColor: "#705c30",
    width: 72,
    height: 50,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#705c30",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },
  orderBadgeContainerHidden: {
    opacity: 0,
    borderWidth: 1.5,
    borderColor: "transparent",
    shadowColor: "transparent",
    elevation: 0,
  },
  orderBadgeText: {
    color: "#705c30",
    fontSize: 14,
    fontWeight: "800",
    textAlign: "center",
  },
  badgeContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  teamBadge: {
    backgroundColor: "#4a7c59",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
  },
  teamBadgeText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  positionBadge: {
    backgroundColor: "#ffffff",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "rgba(74, 124, 89, 0.3)",
  },
  positionBadgeText: {
    color: "#4a7c59",
    fontSize: 14,
    fontWeight: "700",
  },
  infoBadge: {
    backgroundColor: "rgba(112, 92, 48, 0.08)",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
  },
  infoBadgeText: {
    color: "#705c30",
    fontSize: 14,
    fontWeight: "700",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginBottom: 16,
    marginTop: 32,
    paddingHorizontal: 4,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#2e3230",
    fontFamily: "serif",
  },
  sectionSubtitle: {
    fontSize: 12,
    fontWeight: "700",
    color: "#705c30",
    letterSpacing: 0.8,
  },
  radarCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 12, // Reduced padding to allow chart to grow
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    shadowColor: "rgba(46, 50, 48, 1)",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 4,
    width: "100%",
  },
  statGrid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 16,
    minHeight: 110,
    justifyContent: "space-between",
    shadowColor: "rgba(46, 50, 48, 1)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#705c30",
    letterSpacing: 0.3,
    marginBottom: 4,
  },
  statValueContainer: {
    alignItems: "baseline",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 2,
  },
  statValue: {
    fontSize: 26,
    fontWeight: "700",
    color: "#2e3230",
  },
  statValueLarge: {
    fontSize: 30,
    fontWeight: "800",
    color: "#4a7c59",
  },
  statUnit: {
    fontSize: 11,
    fontWeight: "600",
    color: "#4a7c59",
  },
  statIndicator: {
    height: 3,
    width: 24,
    backgroundColor: "#4a7c59",
    marginTop: 4,
    borderRadius: 1.5,
  },
  secondaryStatCard: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 16,
    minHeight: 110,
    justifyContent: "space-between",
    shadowColor: "rgba(46, 50, 48, 1)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  detailStatGrid: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: "rgba(46, 50, 48, 1)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  detailStatRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  detailStatLabel: {
    fontSize: 13,
    color: "#705c30",
    fontWeight: "500",
  },
  detailStatValue: {
    fontSize: 14,
    color: "#2e3230",
    fontWeight: "700",
  },
  gameLogCard: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 12,
    marginBottom: 20,
    shadowColor: "rgba(46, 50, 48, 1)",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  gameLogHeader: {
    flexDirection: "row",
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    marginBottom: 8,
  },
  gameLogHeaderText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#705c30",
    flex: 1,
    textAlign: "center",
  },
  gameLogRow: {
    flexDirection: "row",
    paddingVertical: 8,
    alignItems: "center",
  },
  gameLogText: {
    fontSize: 12,
    color: "#2e3230",
    flex: 1,
    textAlign: "center",
  },
  gameLogBadge: {
    backgroundColor: "rgba(74, 124, 89, 0.1)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  gameLogBadgeText: {
    fontSize: 10,
    color: "#4a7c59",
    fontWeight: "600",
  },
  actionButton: {
    width: "100%",
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "rgba(74, 124, 89, 0.2)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 8,
    marginBottom: 20,
  },
  actionButtonText: {
    color: "#4a7c59",
    fontSize: 16,
    fontWeight: "600",
  },
});
