import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#faf6f0",
    paddingTop: 40,
  },
  container: {
    flex: 1,
    backgroundColor: "#faf6f0",
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  scrollContent: {
    paddingTop: 10,
    paddingBottom: 100,
  },

  // --- 최상단: 팀 기본 정보 섹션 ---
  teamInfoSection: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
  },
  teamInfoCard: {
    backgroundColor: "#4a7c59", // 팀 메인 컬러 (초록색 계열)
    borderRadius: 24,
    padding: 24,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 8,
  },
  teamLogoPlaceholder: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 20,
  },
  teamLogoText: {
    fontSize: 28,
    color: "#ffffff",
    fontWeight: "bold",
  },
  teamTextContainer: {
    flex: 1,
  },
  teamName: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: 4,
  },
  teamTrait: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.8)",
    fontWeight: "500",
    lineHeight: 20,
  },

  // --- 상단: 베스트 라인업 (야구장 UI) ---
  fieldSection: {
    padding: 16,
  },
  fieldCard: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 16,
    alignItems: "center",
    shadowColor: "#2e3230",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 4,
  },
  sectionHeader: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  sectionTitle: {
    color: "#4a7c59",
    fontSize: 18,
    fontWeight: "bold",
  },
  badge: {
    backgroundColor: "rgba(74, 124, 89, 0.1)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  badgeText: {
    color: "#4a7c59",
    fontSize: 12,
    fontWeight: "800",
  },

  fieldContainer: {
    width: width - 64,
    height: (width - 64) * 1.1,
    backgroundColor: "#1d3557",
    borderRadius: 20,
    overflow: "hidden",
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  stadiumFan: {
    width: (width - 64) * 1.6,
    height: (width - 64) * 1.6,
    backgroundColor: "#76c893",
    borderRadius: (width - 64) * 0.8,
    position: "absolute",
    top: -((width - 64) * 0.4),
    transform: [{ rotate: "45deg" }],
    borderWidth: 2,
    borderColor: "#ffffff",
  },
  infieldDirtSemi: {
    position: "absolute",
    bottom: "5%",
    width: (width - 64) * 0.75,
    height: (width - 64) * 0.75,
    backgroundColor: "#f4a261",
    borderRadius: (width - 64) * 0.375,
    alignSelf: "center",
  },
  diamondBaseLines: {
    position: "absolute",
    bottom: "12%",
    width: (width - 64) * 0.4,
    height: (width - 64) * 0.4,
    borderWidth: 4,
    borderColor: "#ffffff",
    transform: [{ rotate: "45deg" }],
    backgroundColor: "#52b788",
  },
  pitcherMoundDirt: {
    position: "absolute",
    top: "60%",
    left: "40%",
    width: "20%",
    height: "20%",
    backgroundColor: "#e76f51",
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  moundPlate: {
    width: "60%",
    height: "15%",
    backgroundColor: "#ffffff",
  },
  baseMarker: {
    position: "absolute",
    width: 12,
    height: 12,
    backgroundColor: "#ffffff",
    transform: [{ rotate: "45deg" }],
    zIndex: 5,
  },
  base1B: { bottom: "31.1%", right: "21.7%", marginRight: -6 },
  base2B: { bottom: "56.8%", alignSelf: "center", marginBottom: -6 },
  base3B: { bottom: "31.1%", left: "21.7%", marginLeft: -6 },
  baseHome: {
    position: "absolute",
    bottom: "5.4%",
    alignSelf: "center",
    width: 16,
    height: 16,
    backgroundColor: "#ffffff",
    transform: [{ rotate: "45deg" }],
  },

  // 포지션 슬롯 좌표 (동일하게 유지)
  posP: { position: "absolute", bottom: "25%", alignSelf: "center" },
  posC: { position: "absolute", bottom: "3%", alignSelf: "center" },
  pos1B: { position: "absolute", bottom: "38%", right: "5%" },
  pos2B: { position: "absolute", bottom: "50%", right: "24%" },
  pos3B: { position: "absolute", bottom: "38%", left: "5%" },
  posSS: { position: "absolute", bottom: "50%", left: "25%" },
  posLF: { position: "absolute", bottom: "70%", left: "12%" },
  posCF: { position: "absolute", bottom: "82%", alignSelf: "center" },
  posRF: { position: "absolute", bottom: "70%", right: "12%" },
  posDH: { position: "absolute", bottom: "15%", right: "5%" },

  slotStadium: {
    paddingHorizontal: 6,
    paddingVertical: 4,
    alignItems: "center",
    minWidth: 48,
    borderRadius: 6,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderWidth: 1.2,
    borderColor: "#1d3557",
    elevation: 3,
  },
  slotPosStadium: {
    fontSize: 8,
    fontWeight: "900",
    color: "#e76f51",
    marginBottom: 1,
  },
  slotNameStadium: {
    fontSize: 10,
    fontWeight: "bold",
    color: "#1d3557",
  },

  // --- 하단: 팀원 리스트 ---
  listSection: {
    padding: 16,
  },
  listCard: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 20,
    shadowColor: "#2e3230",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 2,
  },
  memberItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(46, 50, 48, 0.05)",
  },
  memberInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  memberAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(74, 124, 89, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  memberAvatarText: {
    color: "#4a7c59",
    fontWeight: "bold",
    fontSize: 16,
  },
  memberName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#2e3230",
  },
  memberPos: {
    fontSize: 12,
    color: "#705c30",
    marginTop: 2,
    fontWeight: "600",
  },
  memberNum: {
    fontSize: 14,
    fontWeight: "800",
    color: "#4a7c59",
    backgroundColor: "#f0f7f2",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    overflow: "hidden",
  },
  emptyText: {
    textAlign: "center",
    color: "rgba(46, 50, 48, 0.3)",
    marginTop: 20,
    fontSize: 14,
  },
});
